# Generated by Django 2.2.12 on 2020-09-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(max_length=11, verbose_name='账号')),
                ('password', models.CharField(max_length=10, verbose_name='密码')),
            ],
        ),
    ]
